# Generated by Django 4.1.4 on 2023-01-13 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('emotion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Dataset',
            },
        ),
        migrations.CreateModel(
            name='Emotion_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Emotion_Category',
            },
        ),
        migrations.CreateModel(
            name='Genre_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genre_Category',
            },
        ),
        migrations.CreateModel(
            name='Recommend_Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('thumnail', models.CharField(default='', max_length=200)),
                ('link_url', models.TextField(default='')),
                ('viewCount', models.IntegerField()),
                ('emotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmotionBoard.emotion_category')),
            ],
            options={
                'verbose_name_plural': 'Recommend_Youtube',
            },
        ),
        migrations.CreateModel(
            name='Movie_Drama_Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('thumnail', models.CharField(default='', max_length=200)),
                ('genre', models.ManyToManyField(blank=True, to='EmotionBoard.genre_category')),
            ],
            options={
                'verbose_name_plural': 'Movie_Drama_Recommend',
            },
        ),
        migrations.CreateModel(
            name='DiaryTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(max_length=50)),
                ('diary_img', models.ImageField(blank=True, upload_to='diary/images/%Y/%m/%d/')),
                ('diary_content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DiaryTemp',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(max_length=50)),
                ('diary_img', models.ImageField(blank=True, upload_to='diary/images/%Y/%m/%d/')),
                ('diary_content', models.TextField()),
                ('angry_percent', models.FloatField(default=0.0)),
                ('terror_percent', models.FloatField(default=0.0)),
                ('sadness_percent', models.FloatField(default=0.0)),
                ('loathing_percent', models.FloatField(default=0.0)),
                ('shock_percent', models.FloatField(default=0.0)),
                ('expect_percent', models.FloatField(default=0.0)),
                ('pleasure_percent', models.FloatField(default=0.0)),
                ('calmness_percent', models.FloatField(default=0.0)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_emotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmotionBoard.emotion_category')),
            ],
            options={
                'verbose_name_plural': 'Diary',
            },
        ),
    ]
