# Generated by Django 4.1.4 on 2023-01-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0002_alter_diary_diary_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_drama_recommend',
            name='released_date',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
