# Generated by Django 4.1.4 on 2023-01-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0003_movie_drama_recommend_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarytemp',
            name='diary_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
