# Generated by Django 4.1.4 on 2023-01-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0004_alter_diarytemp_diary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
