# Generated by Django 4.1.4 on 2023-01-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0005_alter_diary_diary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_youtube',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
