# Generated by Django 4.1.4 on 2023-01-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0008_alter_diary_write_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarytemp',
            name='write_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
