# Generated by Django 4.1.4 on 2023-01-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0009_diarytemp_write_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user_select_emotion',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
