# Generated by Django 4.1.4 on 2023-01-25 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0012_rename_emotion_dataset_final_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='user_select_emotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_select_emotion', to='EmotionBoard.emotion_category'),
        ),
    ]
