# Generated by Django 4.1.4 on 2023-01-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0013_alter_diary_user_select_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectGenreForEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmotionBoard.emotion_category')),
                ('genre', models.ManyToManyField(blank=True, to='EmotionBoard.genre_category')),
            ],
            options={
                'verbose_name_plural': 'User_Select_Genre_For_Emotion',
            },
        ),
    ]
