# Generated by Django 4.1.4 on 2023-01-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionBoard', '0014_userselectgenreforemotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend_youtube',
            old_name='viewCount',
            new_name='goodCount',
        ),
    ]
