# Generated by Django 4.1.4 on 2022-12-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superuser',
            new_name='is_admin',
        ),
    ]
