# Generated by Django 4.1.4 on 2022-12-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_rename_is_superuser_account_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
